---
services:
  homepage:
    image: gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - /opt/dockerapps/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
      - /opt/public/images:/app/public/images
      - /media:/media
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Los_Angeles
      - HOMEPAGE_ALLOWED_HOSTS=${MY_DOMAIN}
    restart: unless-stopped
  watchtower:
    image: ghcr.io/nicholas-fedor/watchtower
    container_name: watchtower
    user: 0:0
    environment:
      - TZ=America/Los_Angeles
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_HTTP_API_ENDPOINTS=metrics
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - /media/torrents:/media/torrents
    restart: unless-stopped
    user: 1000:1002
    environment:
      - TZ=America/Los_Angeles
      - UN_START_DELAY=10s
      - UN_RETRY_DELAY=2m
      - UN_MAX_RETRIES=3
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=${SONARR_API_KEY}
      - UN_SONARR_0_PATHS_0=/media/torrents
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=${RADARR_API_KEY}
      - UN_RADARR_0_PATHS_0=/media/torrents
      - UN_RADARR_0_PROTOCOLS=torrent
    security_opt:
      - no-new-privileges:true
  monitoring:
    image: nicolargo/glances:latest
    container_name: monitoring
    restart: always
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Uncomment the below line if you want glances to display host OS detail instead of container's
      - /etc/os-release:/etc/os-release:ro
      - /opt/dockerapps/glances:/glances/conf
    environment:
      - "GLANCES_OPT=-w"
      - TZ=America/Los_Angeles
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    user: 0:0
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=America/Los_Angeles
    volumes:
      - /opt/dockerapps/scrutiny/config:/opt/scrutiny/config
      - /opt/dockerapps/scrutiny/influxdb:/opt/scrutiny/influxdb
      - /run/udev:/run/udev:ro
    devices:
      - /dev/nvme0:/dev/nvme0
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
      - /dev/sdf:/dev/sdf
      - /dev/sdg:/dev/sdg
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /opt/dockerapps/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Los_Angeles
    restart: unless-stopped
  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    environment:
      - TZ=America/Los_Angeles
    restart: unless-stopped
