- Monitoring:
    - CPU Usage:
        icon: mdi-cpu-64-bit
        widget:
          type: glances
          version: 4
          url: http://monitoring:61208
          metric: cpu
    - Mem Usage:
        icon: mdi-memory
        widget:
          type: glances
          version: 4
          url: http://monitoring:61208
          metric: memory
    - Networking:
        icon: mdi-network-outline
        widget:
          type: glances
          version: 4
          url: http://monitoring:61208
          metric: network:eth0
    - Drive Health:
        icon: scrutiny.png
        container: scrutiny
        server: socket-proxy
        href: https://scrutiny.snorlax.media/
        widget:
          type: scrutiny
          url: http://scrutiny:8080
- Media:
    - Plex:
        icon: plex.png
        description: For streaming media
        service: docker
        siteMonitor: https://plex.snorlax.media/
        container: plex
        server: socket-proxy
        widget:
          type: tautulli
          url: http://tautulli:8181
          key: "{{HOMEPAGE_VAR_TAUTULLI_KEY}}"
    - Overseerr:
        icon: overseerr.png
        href: https://overseerr.snorlax.media/
        description: For requesting media
        siteMonitor: https://overseerr.snorlax.media/
        service: docker
        container: overseerr
        server: socket-proxy
        widget:
          type: overseerr
          url: http://overseerr:5055
          key: "{{HOMEPAGE_VAR_OVERSEERR_KEY}}"
    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.snorlax.media/
        description: For TV download scheduling
        siteMonitor: https://sonarr.snorlax.media/
        service: docker
        container: sonarr
        server: socket-proxy
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: "{{HOMEPAGE_VAR_SONARR_KEY}}"
    - Radarr:
        icon: radarr.png
        href: https://radarr.snorlax.media/
        description: For movie download scheduling
        siteMonitor: https://radarr.snorlax.media/
        service: docker
        container: radarr
        server: socket-proxy
        widget:
          type: radarr
          url: http://radarr:7878
          key: "{{HOMEPAGE_VAR_RADARR_KEY}}"
    - Bazarr:
        icon: bazarr.png
        href: https://bazarr.snorlax.media/
        description: For subtitle management
        siteMonitor: https://bazarr.snorlax.media/
        service: docker
        container: bazarr
        server: socket-proxy
        widget:
          type: bazarr
          url: http://bazarr:6767
          key: "{{HOMEPAGE_VAR_BAZARR_KEY}}"

- Torrenting:
    - Prowlarr:
        icon: prowlarr.png
        href: https://prowlarr.snorlax.media/
        description: For torrent indexers
        siteMonitor: https://prowlarr.snorlax.media/
        container: prowlarr
        server: socket-proxy
        widget:
          type: prowlarr
          url: http://prowlarr:9696
          key: "{{HOMEPAGE_VAR_PROWLARR_KEY}}"
    - Qbittorrent:
        icon: qbittorrent.png
        href: https://qbittorrent.snorlax.media/
        description: For downloading torrents
        siteMonitor: https://qbittorrent.snorlax.media/
        container: qbittorrent
        server: socket-proxy
        widget:
          type: qbittorrent
          url: http://qbittorrent:8123
          username: "{{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}"
          password: "{{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}"

- Auth:
    - Caddy:
        icon: caddy.png
        description: For reverse proxy
        container: caddy
        server: socket-proxy
        widget:
          type: caddy
          url: http://proxy:32080
    - Authelia:
        icon: authelia.png
        href: https://auth.snorlax.media/
        description: For 2FA and SSO
        siteMonitor: https://auth.snorlax.media/
        container: auth
        server: socket-proxy
